### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by Andershouston** [sonburn/symbol-instance-sheet#7]
Appears to not be working correctly after upgrading to Sketch 50.2

**Comment by sonburn** [comment]
@andershouston you are going to have to give me a little more information than that... a screenshot or description of the problem.

**Comment by Andershouston** [comment]
Here's what's happening to me.

**Comment by sonburn** [comment]
@Andershouston Not sure if your whole response was submitted, but again I have nothing to go on to help diagnose any issue you are experiencing.

**Comment by Andershouston** [comment]
Perhaps not, did you not see the images I sent you?

**Comment by Andershouston** [comment]
Yes, it's how I'm able to maintain clear distinctions in a larger document.

**Comment by sonburn** [comment]
@Andershouston This is actually a known issue, or current limitation of the plugin (see https://github.com/sonburn/symbol-instance-sheet/issues/2). I do plan to address this in a future update. Since an issue/enhancement already exists for this issue, I am going to go ahead and close this one. Thanks for the feedback, and using the plugin.
